void import('/router.js');

(()=>{'use strict';
const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const loader=$('.loader');const hideLoader=()=>loader?.classList.add('is-hidden');window.addEventListener('load',()=>setTimeout(hideLoader,160),{once:true});setTimeout(hideLoader,1800);
const menu=$('#mobileMenu'),open=$('#menuOpen'),close=$('#menuClose');function setMenu(on){if(!menu)return;menu.classList.toggle('open',on);menu.setAttribute('aria-hidden',String(!on));open?.setAttribute('aria-expanded',String(on));document.body.classList.toggle('menu-open',on)}open?.addEventListener('click',()=>setMenu(true));close?.addEventListener('click',()=>setMenu(false));$$('#mobileMenu a').forEach(a=>a.addEventListener('click',()=>setMenu(false)));document.addEventListener('keydown',e=>{if(e.key==='Escape')setMenu(false)});
const reveals=$$('.reveal');if('IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.06});reveals.forEach(el=>io.observe(el))}else reveals.forEach(el=>el.classList.add('visible'));
$$('.filter-btn').forEach(btn=>btn.addEventListener('click',()=>{$$('.filter-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.filter;$$('[data-cat]').forEach(card=>card.classList.toggle('is-hidden',f!=='all'&&!card.dataset.cat.split(' ').includes(f)))}));
const time=$('#heroTime');if(time){const tick=()=>time.textContent=new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date())+' IST';tick();setInterval(tick,1000)}
if(location.pathname==='/tva/lab')requestAnimationFrame(()=>$('#experiment-lab')?.scrollIntoView({block:'start'}));

const caseStudies={
 nexora:{title:'NEXORA',subtitle:'Brand identity — from wireframe to final 3D render.',url:'/tva/project-nexora',steps:[['01','Wireframe & Concept','Initial layout exploration, grid systems and typographic hierarchy mapped in low-fidelity wireframes.'],['02','3D Model & Blocking','Crystalline geometry built in Blender — material tests, lighting rigs and camera blocking for hero assets.'],['03','Final Render','Polished renders with gradient lighting, colour grading and export for digital deliverables.']]},
 chronex:{title:'CHRONEX',subtitle:'Luxury watch product render — full production pipeline.',url:'/tva/project-chronex',steps:[['01','Reference & Wireframe','Dial proportions, bezel geometry and material references gathered. Block-out wireframe for accurate scale.'],['02','3D Model & Materials','High-poly modelling with PBR materials — brushed steel, sapphire crystal and leather strap texturing.'],['03','Final Render','Cinematic lighting setup, depth of field and post-processing for photorealistic product imagery.']]}
};
function ensureModal(){if($('#caseModal'))return;const m=document.createElement('div');m.id='caseModal';m.className='case-modal';m.setAttribute('role','dialog');m.setAttribute('aria-modal','true');m.setAttribute('aria-hidden','true');m.innerHTML='<div class="case-overlay"></div><div class="case-panel"><button class="case-close" aria-label="Close">×</button><p class="tech-label"><span>PROCESS FILE</span> BEHIND THE SCENES</p><h2 id="caseTitle"></h2><p class="lead" id="caseSub"></p><div id="caseSteps"></div><div class="record-actions"><a class="btn" id="caseLink">View full project →</a><button class="btn ghost" id="caseCloseBottom">Close</button></div></div>';document.body.appendChild(m);m.querySelector('.case-overlay').onclick=closeModal;m.querySelector('.case-close').onclick=closeModal;$('#caseCloseBottom').onclick=closeModal}
let lastTrigger=null;function openModal(key,trigger){const d=caseStudies[key];if(!d)return;ensureModal();lastTrigger=trigger;$('#caseTitle').textContent=d.title;$('#caseSub').textContent=d.subtitle;$('#caseLink').href=d.url;$('#caseSteps').innerHTML=d.steps.map(s=>`<div class="case-step"><b>${s[0]}</b><strong>${s[1]}</strong><p>${s[2]}</p></div>`).join('');const m=$('#caseModal');m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.classList.add('menu-open');m.querySelector('.case-close').focus()}function closeModal(){const m=$('#caseModal');if(!m)return;m.classList.remove('open');m.setAttribute('aria-hidden','true');document.body.classList.remove('menu-open');lastTrigger?.focus()}
document.addEventListener('click',e=>{const t=e.target.closest('[data-case]');if(t){e.preventDefault();openModal(t.dataset.case,t)}});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});

function fit(c){const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=Math.max(1,Math.round(r.width*d));c.height=Math.max(1,Math.round(r.height*d));const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);return{x,w:r.width,h:r.height}}
function drawCanvas(c){const type=c.dataset.visual||c.dataset.project||'grid',motion=c.dataset.motion==='true';let raf=0,t=0;const paint=()=>{const{x,w,h}=fit(c);x.clearRect(0,0,w,h);x.fillStyle='#0d0c0a';x.fillRect(0,0,w,h);const glow=x.createRadialGradient(w*.52,h*.48,0,w*.52,h*.48,Math.max(w,h)*.55);glow.addColorStop(0,'rgba(212,113,43,.20)');glow.addColorStop(1,'transparent');x.fillStyle=glow;x.fillRect(0,0,w,h);x.strokeStyle='rgba(216,198,165,.13)';x.lineWidth=1;for(let i=0;i<8;i++){x.beginPath();x.moveTo(i*w/7,0);x.lineTo(i*w/7,h);x.stroke()}for(let i=0;i<6;i++){x.beginPath();x.moveTo(0,i*h/5);x.lineTo(w,i*h/5);x.stroke()}x.strokeStyle='rgba(212,113,43,.75)';x.fillStyle='rgba(169,86,32,.2)';x.lineWidth=2;if(type.includes('nexora')||type==='hex'){const r=Math.min(w,h)*.24,a=t*.15;x.beginPath();for(let i=0;i<6;i++){const q=a+i*Math.PI/3,px=w/2+Math.cos(q)*r,py=h/2+Math.sin(q)*r;i?x.lineTo(px,py):x.moveTo(px,py)}x.closePath();x.fill();x.stroke();x.beginPath();x.moveTo(w*.2,h*.8);x.lineTo(w*.8,h*.2);x.stroke()}else if(type.includes('chronex')||type.includes('watch')){const r=Math.min(w,h)*.27,cx=w/2,cy=h/2;x.beginPath();x.arc(cx,cy,r,0,Math.PI*2);x.fill();x.stroke();for(let i=0;i<12;i++){const a=i*Math.PI/6;x.beginPath();x.moveTo(cx+Math.cos(a)*r*.78,cy+Math.sin(a)*r*.78);x.lineTo(cx+Math.cos(a)*r,cy+Math.sin(a)*r);x.stroke()}x.beginPath();x.moveTo(cx,cy);x.lineTo(cx+Math.cos(t)*r*.62,cy+Math.sin(t)*r*.62);x.stroke()}else if(type.includes('echoes')){for(let i=1;i<7;i++){x.beginPath();x.arc(w/2,h/2,((i*28+t*18)%Math.max(40,Math.min(w,h)*.55)),0,Math.PI*2);x.globalAlpha=.75-i*.08;x.stroke()}x.globalAlpha=1}else{for(let i=0;i<5;i++){const s=Math.min(w,h)*(.12+i*.055),a=t*.08+i;x.save();x.translate(w/2,h/2);x.rotate(a);x.strokeRect(-s/2,-s/2,s,s*1.25);x.restore()}x.font=`600 ${Math.max(18,w*.06)}px Barlow Condensed`;x.textAlign='center';x.fillStyle='rgba(216,198,165,.45)';x.fillText((c.dataset.label||type).toUpperCase(),w/2,h*.88)}t+=.012;if(motion)raf=requestAnimationFrame(paint)};paint();if(!motion){let timer;addEventListener('resize',()=>{clearTimeout(timer);timer=setTimeout(paint,120)})}return()=>cancelAnimationFrame(raf)}$$('canvas[data-visual],canvas[data-project]').forEach(drawCanvas);

const idScene=$('[data-tva-id-card]');if(idScene){const idCard=$('.tva-id-card',idScene),reduced=matchMedia('(prefers-reduced-motion:reduce)').matches,clamp=(n,min,max)=>Math.min(max,Math.max(min,n));let currentX=0,currentY=0,currentHoverX=0,currentHoverY=0,targetX=0,targetY=0,targetHoverX=0,targetHoverY=0,startX=0,startY=0,startRotationX=0,startRotationY=0,dragDistance=0,dragging=false,raf=0;const updateLabel=()=>{const back=Math.abs(Math.round(targetY/180))%2===1;idScene.setAttribute('aria-pressed',String(back));idScene.setAttribute('aria-label',`Interactive TVA identification card showing the ${back?'back':'front'}. Drag to rotate or press Enter to flip.`)};const render=()=>{const ease=reduced?1:.14;currentX+=(targetX-currentX)*ease;currentY+=(targetY-currentY)*ease;currentHoverX+=(targetHoverX-currentHoverX)*ease;currentHoverY+=(targetHoverY-currentHoverY)*ease;idCard.style.transform=`rotateX(${currentX+currentHoverX}deg) rotateY(${currentY+currentHoverY}deg)`;const moving=Math.abs(targetX-currentX)+Math.abs(targetY-currentY)+Math.abs(targetHoverX-currentHoverX)+Math.abs(targetHoverY-currentHoverY);if(moving>.02)raf=requestAnimationFrame(render);else raf=0};const schedule=()=>{if(!raf)raf=requestAnimationFrame(render)};const flip=()=>{targetY=Math.round(targetY/180)*180+180;targetX=0;updateLabel();schedule()};idScene.addEventListener('pointerdown',e=>{if(e.button!==0)return;dragging=true;dragDistance=0;startX=e.clientX;startY=e.clientY;startRotationX=targetX;startRotationY=targetY;targetHoverX=targetHoverY=0;idScene.classList.add('is-dragging');idScene.setPointerCapture(e.pointerId);schedule()});idScene.addEventListener('pointermove',e=>{if(dragging){const dx=e.clientX-startX,dy=e.clientY-startY;dragDistance=Math.max(dragDistance,Math.hypot(dx,dy));targetY=startRotationY+dx*.72;targetX=clamp(startRotationX-dy*.22,-18,18);if(Math.abs(dx)>Math.abs(dy))e.preventDefault();schedule();return}if(e.pointerType==='mouse'){const r=idScene.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;targetHoverY=x*10;targetHoverX=-y*7;schedule()}});const release=e=>{if(!dragging)return;dragging=false;idScene.classList.remove('is-dragging');if(idScene.hasPointerCapture(e.pointerId))idScene.releasePointerCapture(e.pointerId);targetHoverX=targetHoverY=0;if(dragDistance<7)targetY=Math.round(targetY/180)*180+180;else targetY=Math.round(targetY/180)*180;targetX=0;updateLabel();schedule()};idScene.addEventListener('pointerup',release);idScene.addEventListener('pointercancel',release);idScene.addEventListener('pointerleave',()=>{if(!dragging){targetHoverX=targetHoverY=0;schedule()}});idScene.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!e.repeat){e.preventDefault();flip()}});updateLabel()}

const form=$('#contactForm');if(form){const btn=$('#formSubmitBtn'),ok=$('#formSuccess'),bad=$('#formError'),key='kushal_form_cooldown_until',cool=10000;let timer;const ready=()=>{btn.textContent='Send Message →';btn.disabled=false};const cooldown=ms=>{btn.disabled=true;let n=Math.ceil(ms/1000);clearInterval(timer);const tick=()=>{if(n<=0){clearInterval(timer);localStorage.removeItem(key);ready()}else btn.textContent=`Wait ${n--}s`};tick();timer=setInterval(tick,1000)};const remaining=parseInt(localStorage.getItem(key)||'0',10)-Date.now();if(remaining>0){ok.classList.add('show');cooldown(remaining)}form.addEventListener('submit',async e=>{e.preventDefault();const fname=$('#fname').value.trim(),email=$('#email').value.trim(),msg=$('#msg').value.trim();if(!fname||!email||!msg){alert('Please fill in your name, email and message.');return}btn.textContent='Sending…';btn.disabled=true;ok.classList.remove('show');bad.classList.remove('show');try{const res=await fetch(form.action,{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}});if(!res.ok)throw new Error('Submit failed');ok.classList.add('show');form.reset();const until=Date.now()+cool;localStorage.setItem(key,String(until));cooldown(cool)}catch(err){bad.classList.add('show');ready()}})}
})();
